### DISCUSSION TITLE
Automatically generate NAV menu

### DISCUSSION THREAD

**Discussion by JakubAndrysek** [JakubAndrysek/MkDoxy#40] [Ideas]
Plugin will automatically generate navigation links in the placeholder position

Example of `mkdocs.yaml`
```yaml
...
nav:
  - Home: 'README.md'
  - MkDocs API:
      - ::: mkdoxyApi
```

Will generate:
```yaml
nav:
  - Home: 'README.md'
  - MkDocs API:
      - mkdoxyApi/index.md
      - 'Links': 'mkdoxyApi/links.md'
      - 'Classes':
          - 'Class List': 'mkdoxyApi/annotated.md'
          - 'Class Index': 'mkdoxyApi/classes.md'
          - 'Class Hierarchy': 'mkdoxyApi/hierarchy.md'
          - 'Class Members': 'mkdoxyApi/class_members.md'
          - 'Class Member Functions': 'mkdoxyApi/class_member_functions.md'
          - 'Class Member Variables': 'mkdoxyApi/class_member_variables.md'
          - 'Class Member Typedefs': 'mkdoxyApi/class_member_typedefs.md'
          - 'Class Member Enumerations': 'mkdoxyApi/class_member_enums.md'
      - 'Namespaces':
          - 'Namespace List': 'mkdoxyApi/namespaces.md'
          - 'Namespace Members': 'mkdoxyApi/namespace_members.md'
          - 'Namespace Member Functions': 'mkdoxyApi/namespace_member_functions.md'
          - 'Namespace Member Variables': 'mkdoxyApi/namespace_member_variables.md'
          - 'Namespace Member Typedefs': 'mkdoxyApi/namespace_member_typedefs.md'
          - 'Namespace Member Enumerations': 'mkdoxyApi/namespace_member_enums.md'
      - 'Functions': 'mkdoxyApi/functions.md'
      - 'Variables': 'mkdoxyApi/variables.md'
      - 'Macros': 'mkdoxyApi/macros.md'
      - 'Files': 'mkdoxyApi/files.md'
```

With parameters:
```yaml
nav:
  - Home: 'README.md'
  - MkDocs API:
      - ::: mkdoxyApi
        enable:
          - classes
          - functions
          - variables
        disable:
          - namespaces
          - macros
```
