### DISCUSSION TITLE
Support absolute path in templates

### DISCUSSION THREAD

**Discussion by JakubAndrysek** [JakubAndrysek/MkDoxy#56] [Ideas]
It is possible trought more ways:
## 1. Jinja template

```py
from mkdocs.plugins import BasePlugin
from mkdocs.config import config_options
from jinja2 import Environment

class AbsoluteLinkPlugin(BasePlugin):

    config_scheme = (
        ('site_url', config_options.Type(str, required=True)),
    )

    def absolute_link(self, site_url, path):
        site_url = site_url.rstrip('/')
        return f"{site_url}/{path.lstrip('/')}"

    def on_env(self, env, config, **kwargs):
        env.filters['absolute_link'] = self.absolute_link
        return env
```

```yaml
plugins:
  - search
  - absolutelink:
      site_url: "https://www.example.com"
```

```html
<a href="{{ 'my-page/'|absolute_link(config.site_url) }}">Link text</a>

```

## 2. `mkdocs_macros_plugin`

If you want a more automated solution, there isn't a specific plugin for handling absolute links in MkDocs, but you can use a workaround with the mkdocs_macros_plugin. This plugin allows you to create custom macros in your Markdown files that can be replaced with content during the build process.

```yaml
plugins:
  - search
  - macros

site_url: "https://www.example.com"
extra:
  python: "main.py"
```

```py
def define_env(env):
    @env.macro
    def absolute_link(path):
        site_url = env.conf['site_url'].rstrip('/')
        use_directory_urls = env.conf['use_directory_urls']
        
        if path.endswith(".md"):
            path = path[:-3]
            if use_directory_urls:
                path += '/'
            else:
                path += '.html'

        return f"{site_url}/{path.lstrip('/')}"
```

## 3. `pymdownx.pathconverter`

You can use the pymdownx.pathconverter extension to convert relative Markdown links to absolute links, taking into account the use_directory_urls configuration option.

```yaml
site_url: "https://www.example.com"

markdown_extensions:
  - pymdownx.pathconverter:
      base: "https://www.example.com"
```
