### ISSUE TITLE
MkDoxy not invoked in mkdocs-monorepo plugin source tree configuration?

### ISSUE THREAD

**Issue by moschmdt** [JakubAndrysek/MkDoxy#109]
I just tested mkdoxy with [mkdocs-monorepo plugin](https://github.com/backstage/mkdocs-monorepo-plugin) with the [source-tree][st] configuration. Unfortunately, it seems that the mkdoxy toolchain (?) is not invoked if the mkdoxy is configured in a sub project.

I do not see any `INFO - -> Start project belly-rubs` in the output log from MkDoxy. Thus, I assume that the project/ plugin is not invoked? I did ensure that MkDoxy works fine on my system.
Might this be a monorepo issue?

This is the copy of the monorepo [source-tree][st] setup and extended:
```
$ tree .

├── components
│   ├── belly-rubs
│   │   ├── docs
│   │   |   └── index.md
│   │   ├── src
│   │   |   └── main.cpp
│   │   ├── include
│   │   |   └── header.hpp
│   │   └── mkdocs.yml
├── docs
│   └── index.md
└── mkdocs.yml

8 directories, 8 files
```

I have the configuration of the `mkdoxy` project configuration in the subproject (source folder), e.g. 
`components/belly-rubs/mkdocs.yml`:

```yaml
site_name: belly-rubs

theme:
  name: material

nav:
    - index.md
    - Links: belly-rubs/links.md
    - Classes:
          - Class List: belly-rubs/annotated.md
          - Class Index: belly-rubs/classes.md
          - Class Hierarchy: belly-rubs/hierarchy.md
          - Class Members: belly-rubs/class_members.md
          - Class Member Functions: belly-rubs/class_member_functions.md
          - Class Member Variables: belly-rubs/class_member_variables.md
          - Class Member Typedefs: belly-rubs/class_member_typedefs.md
          - Class Member Enumerations: belly-rubs/class_member_enums.m

plugins:
    - search
    - mkdoxy:
          projects:
              belly-rubs:
                  src-dirs: include/ src/
                  full-doc: True
                  doxy-cfg:
                      FILE_PATTERNS: "*.cpp *.hpp"
                      RECURSIVE: True
                      EXTRACT_ALL: True

```

and the main `mkdocs.yaml`:

```yaml
site_name: Cats System

nav:
  - Intro: 'index.md'
  - Components: '*include ./components/*/mkdocs.yml'
  
plugins:
    - search
    - img2figv2
    - monorepo

```

Used mkdocs versions:

```
mkdocs==1.6.0
mkdocs-get-deps==0.2.0
mkdocs-img2figv2-plugin==0.0.2
mkdocs-macros-plugin==1.0.5
mkdocs-material==9.5.25
mkdocs-material-extensions==1.3.1
mkdocs-monorepo-plugin==1.1.0
mkdoxy==1.2.4
```

[st]: https://github.com/backstage/mkdocs-monorepo-plugin?tab=readme-ov-file#example-source-filetree-1
