### ISSUE TITLE
All Doxygen configs seems not be working

### ISSUE THREAD

**Issue by curiousmindflow** [JakubAndrysek/MkDoxy#118]
Hello,

I tried to use some Doxygen configuration keys like this:

```yaml
plugins:
  - mkdoxy:
      projects:
        nodus-ffi:
          src-dirs: target/include
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.h"
            RECURSIVE: True
            EXTRACT_ALL: True
            OPTIMIZE_OUTPUT_FOR_C: True
            SORT_MEMBER_DOCS: NO
            SORT_BRIEF_DOCS: NO
            SORT_GROUP_NAMES: NO
            SORT_BY_SCOPE_NAME: NO
```

But it seems they are not taken into account.

Can you tell me if it's supported ? and if yes, where am i wrong ?

Thank you
