### ISSUE TITLE
Can i use XML by setting path to already generated by doxygen

### ISSUE THREAD

**Issue by MightyMirko** [JakubAndrysek/MkDoxy#128]
HI,

i just tried your plugin

Its inside a podman container. 

```yaml
site_name: My Docs
theme:
  name: mkdocs
plugins:
  - search
  - mkdoxy:
      projects:
        MyProj: # name of project must be alphanumeric + numbers (without spaces)
          src-dirs: /workspace/MyProj/ # path to source code (support multiple paths separated by space) => INPUT
          full-doc: True # if you want to generate full documentation
          doxy-cfg-file: /workspace/docs/builders/Doxyfile # standard doxygen configuration (key: value)
```

I want to automate and one stage before mkdocs is already building latex, html and xml by doxygen. 

Can i reuse the xml files?
