### ISSUE TITLE
Provide doxygen logs

### ISSUE THREAD

**Issue by EmilyBourne** [JakubAndrysek/MkDoxy#130]
Thanks for the project. The basic functionalities worked really well out of the box.

However I am having trouble finding the doxygen logs. In our project, we activate the doxygen warnings and use them in the CI to enforce the documentation of new code. I suspect that the doxygen command is run in a temporary folder which means that the log is lost when the result is copied.

Here is what I tried:
```
  - mkdoxy:
      save-api: ./doxy_api
      projects:
        gyselalibxx:
          src-dirs: ../src
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.cpp *.h*"
            RECURSIVE: True
            EXTRACT_ALL: False
            EXCLUDE_SYMBOLS: "detail details mapping_detail"
            EXTRACT_LOCAL_CLASSES: True
            BUILTIN_STL_SUPPORT: Yes
            CLANG_ASSISTED_PARSING: Yes
            ENUM_VALUES_PER_LINE: 1
            FULL_PATH_NAMES: True
            GENERATE_TREEVIEW: True
            SHOW_FILES: True
            SHOW_INCLUDE_FILES: True
            TYPEDEF_HIDES_STRUCT: True
            WARN_IF_UNDOCUMENTED: True
            WARN_IF_DOC_ERROR: True
            WARN_AS_ERROR: False
            WARN_NO_PARAMDOC: True
            WARN_LOGFILE: "doxygen.log"
```
There is no sign of the `doxygen.log` file in any folder related to mkdocs.

Additionally if I set `WARN_AS_ERROR` to true I seem to get stuck in an infinite loop.

Is there something that I missed or do I need to run doxygen twice (once to check the warnings and once to generate the docs) ?
