### ISSUE TITLE
Disable / enable plugin using ENV variable

### ISSUE THREAD

**Issue by JakubAndrysek** [JakubAndrysek/MkDoxy#34]
Add support to deactivate the plugin using the ENV variable to speed up writing standard documentation without API generation and snippets.

More about [Environment Variables in MkDocs](https://www.mkdocs.org/user-guide/configuration/#environment-variables).
Inspiration from [mkdocs-simple-hooks](https://github.com/aklajnert/mkdocs-simple-hooks/tree/master#disabling-the-plugin)

```yaml
plugins:
  - mkdoxy:
      enabled: !ENV [ENABLE_MKDOXY, True]
      ...
```
