### ISSUE TITLE
Using the details tag

### ISSUE THREAD

**Issue by niosus** [JakubAndrysek/MkDoxy#76]
Hey there! Thanks for an amazing plugin! 

I do have an issue with it though. I am trying to use the `<details>` tag with my generated docs and it fails on me.

If I use the following in my md file:

```
<details>
<summary>my_class</summary>

::: doxy.lidar.Class
    name: my_class
    indent_level: 4

</details>
```

This does not render in mkdocs generated page. It does generate without the details tag. 

I do have all the needed extensions (I think) in my config:
```yaml
markdown_extensions:
  - admonition
  - markdown.extensions.md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: true
  - pymdownx.blocks.details:
  - pymdownx.blocks.html:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
  - pymdownx.tabbed:
      alternate_style: true
```

Any ideas what I might be doing wrong?
