### ISSUE TITLE
Support for diagrams and dot files

### ISSUE THREAD

**Issue by moschmdt** [JakubAndrysek/MkDoxy#83]
Thank you for the plugin - I really like it!

Is it currently supported to generate dot files or diagrams?

I tried it with the following config:

```yml
Project:
  src-dirs: src/
  full-doc: True
  doxy-cfg:
      FILE_PATTERNS: "*.cpp *.hpp"
      RECURSIVE: True
      HAVE_DOT: True
      DOT_IMAGE_FORMAT: svg
      INTERACTIVE_SVG: True
      CLASS_GRAPH: True
      INCLUDE_GRAPH: True
```

Unfortunately, this did not work so far.
